import React from "react";

export const CandidateSignupPage = React.lazy(() => import("../../pages/SignupPage.jsx"));
export const SignupInterviewerPage = React.lazy(() => import("../../pages/InterviewerSignupPage.jsx"));
export const LoginPage = React.lazy(() => import("../../pages/LoginPage.jsx"));
export const HomePage = React.lazy(() => import("../../pages/HomePage.jsx"));
export const MeetingPage = React.lazy(() => import("../../pages/MeetingPage.jsx"));
export const ProductPage = React.lazy(() => import("../../pages/ProductPage.jsx"));
export const AiIntervuePage = React.lazy(() => import("../../pages/AiIntervuePage.jsx"));
export const ResumeBuilderPage = React.lazy(() => import("../../products/resumeBuilder.jsx"));
export const TocPage = React.lazy(() => import("../../pages/TocPage.jsx"));
export const RefundsAndCancellationPage = React.lazy(() => import("../../pages/RefundsAndCancellationPage.jsx"));
export const ContactPage = React.lazy(() => import("../../pages/ContactPage.jsx"));
export const AboutPage = React.lazy(() => import("../../pages/AboutPage.jsx"));
export const PrivacyPolicyPage = React.lazy(() => import("../../pages/PrivacyPolicyPage.jsx"));
export const PricingPage = React.lazy(() => import("../../pages/PricingPage.jsx"));
export const SignUpPage = React.lazy(() => import("../../pages/signupPage2.jsx"));
export const DisplayPage = React.lazy(() => import("../../pages/DisplayPage.jsx"));
export const JobDetailPage = React.lazy(() => import("../../pages/JobDetailPage.jsx"));
export const SignupOrgPage = React.lazy(() => import("../../pages/signupOrg.jsx"));
export const EmployeeProfilePage = React.lazy(() => import("../../pages/EmployeeProfilePage.jsx"));
export const ResumeAnalysisPage = React.lazy(() => import("../../products/resumeAnalysis.jsx"));
export const ThankYou = React.lazy(() => import("../../pages/ThankYou.jsx"));
export const LoginInterviewer = React.lazy(() => import("../../pages/LoginInterviewer.jsx"));
export const LoginInterviewe = React.lazy(() => import("../../pages/LoginInterviewe.jsx"));
